# Generated by Django 4.2.3 on 2024-06-04 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=28)),
                (
                    "length",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1300)]
                    ),
                ),
                (
                    "width",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1000)]
                    ),
                ),
                (
                    "weight",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(450)]
                    ),
                ),
                ("velocity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLACK", "Black"),
                            ("WHITE", "White"),
                            ("GRAY", "Gray"),
                            ("BLUE", "Blue"),
                            ("RED", "Red"),
                            ("BROWN", "Brown"),
                            ("BEIGE", "Beige"),
                            ("ORANGE", "Orange"),
                            ("YELLOW", "Yellow"),
                            ("GOLD", "Gold"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
