# Generated by Django 4.2.3 on 2024-06-04 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carmodel",
            options={"verbose_name_plural": "Cars"},
        ),
    ]
