# Generated by Django 4.2.3 on 2024-06-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_app", "0002_alter_carmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="color",
            field=models.CharField(
                choices=[
                    ("-", "-"),
                    ("BLACK", "Black"),
                    ("WHITE", "White"),
                    ("GRAY", "Gray"),
                    ("BLUE", "Blue"),
                    ("RED", "Red"),
                    ("BROWN", "Brown"),
                    ("BEIGE", "Beige"),
                    ("ORANGE", "Orange"),
                    ("YELLOW", "Yellow"),
                    ("GOLD", "Gold"),
                ],
                max_length=16,
            ),
        ),
    ]
